### ISSUE TITLE
Setting URL Endpoint via config is missing in recent version (for testing purposes with wiremock)

### ISSUE THREAD

**Issue by Santonian** [Adyen/adyen-java-api-library#1061]
We recently switched from v18 to the latest v20 release of the API. Besides a couple of code change, we noticed, that the Endpoint URL of the newly introduced PaymentApi is not changeable via the com.adyen.Config object as before with the Checkout object.

We are running a couple of tests using wiremock for mocking calls to the adyen backend. For this to work, it is necessary to set the endpoint to a specific URL. But this seems to be not possible anymore. 

Did I miss something? Or why is the Endpoint not changeable anymore?

**Comment by jillingk** [comment]
Hi @Santonian,

Thanks for reaching out here! I was not aware about any one using the config endpoint setter to implement mocks, however I see the benefit in that. We removed the endpoints from the config as we started using generated endpoint urls based on OpenAPI specifications. Perhaps instead of using a self specified URL instead you could mock the same way we're doing it in this library, that is by mocking the ClientInterface? You can take a look at our unit tests if you want some inspiration on how that would look like.

If that solution does not work for you we could opt for making the baseURL constants public and not final, however I think I'd rather not as that might cause some confusion later on. Let me know what you would prefer though and we can discuss it further!

Best, Jilling 
Adyen
