### ISSUE TITLE
Setting payment method for tokenized payments after upgrading java library to version 20.0.0

### ISSUE THREAD

**Issue by nenadstojanov** [Adyen/adyen-java-api-library#1066]
**Describe the bug**
We're trying to update library version from 17.2.0 to 20.0.0, but we have troubles to understand what is the best way to set the payment method for tokenized payments. 
- First option is to use CardDetails for the payment method - new CheckoutPaymentMethod(cardDetails). It works ok, and we can appropriately set the type to scheme value. 
- Second option which was pointed as preferred is to use StoredPaymentMethodDetails for the tokenized payments. But none of the types in StoredPaymentMethodDetails.TypeEnum looks appropriate. The request is passing without setting the type though.

There is also a support ticket for this problem - #3938606
In the referenced documentation page, the paymentMethod type is always set to scheme for the tokenized payments.
https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens 

Scheme type is used in the couple of requests for payment with token in the API explorer
https://docs.adyen.com/api-explorer/Checkout/70/post/payments

**Screenshots:**
Here is a screenshot of the StoredPaymentMethodDetails.TypeEnum values
<img width="343" alt="StoredPaymentMethodDetails_TypeEnum" src="https://github.com/Adyen/adyen-java-api-library/assets/84513236/bbf520eb-740d-4636-8df6-69ea7e65a908">

**Desktop :**
 - Java Version: [15.0.2]
 - Library Version: [20.0.0]

**Comment by jillingk** [comment]
Hi @nenadstojanov,

Thanks for reaching out to us here and apologies for the delayed response! You're actually on the right track and the ```CardDetails``` class is the way to go. It might be sometimes that a specific payment method are defined in another class, however usually you can identify the right class by matching the ```type``` param. In this case because you need to populate the type with scheme, the ```CardDetails``` class should be right. 

Let me know if you were able to make it all work!

Best, Jilling
Adyen
