### ISSUE TITLE
CheckoutPaymentMethod Deserialization Problem

### ISSUE THREAD

**Issue by senturkozer** [Adyen/adyen-java-api-library#1085]
**Describe the bug**
I see that onlinebanking_IN and wallet_IN is defined in both BillDeskDetails and PaymentDetails. This causes a problem when deserializing CheckoutPaymentMethod.

**How to reproduce**
Try to deserialize below json.
```json
"paymentMethod": {
    "type": "onlinebanking_IN",
    "issuer": "ATP",
    "checkoutAttemptId": "b99c09dc-71de-46c8-9966-f5e0749e3af916896164054933B5FA15A3D19822122955A9502122D1F560CEC10F9E1B08ACE1D2C4FA5E7D5FD"
  }
```
It gets `The JSON string is invalid for CheckoutPaymentMethod with oneOf schemas: AchDetails, AfterpayDetails, AmazonPayDe...` error since validCount = 2, both BillDeskDetails and PaymentDetails.

**Expected behavior**
It should deserialize to BillDeskDetails.

**Screenshots**
<img width="1428" alt="image" src="https://github.com/Adyen/adyen-java-api-library/assets/89445771/21f5c58b-e578-4b3b-acbb-7581d9fe20f9">

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 20.1.1

**Additional context**
Thank you

**Comment by wboereboom** [comment]
Hi @senturkozer,

I've identified the problem on our source code, and it's getting fixed soon so that we can generate valid without these deserialisation issues.

Hope to be able to roll out this fix for you shortly, and our apologies for any impact this might have had on your implementation.

Kind Regards,
Wouter
Adyen

**Comment by senturkozer** [comment]
Thank you @wboereboom. Can you let us know when the fix is released?

**Comment by senturkozer** [comment]
Do we have any updates on this?

**Comment by jillingk** [comment]
Hey @senturkozer,

Yes we're currently merging a fix on our backend that will trigger the pipelines updating all these libraries shortly after. We should be able to include this fix in the next release this Monday! Apologies for the delay.

Best, Jilling
Adyen

**Comment by senturkozer** [comment]
Hi @jillingk. Is this released? Can we check?

**Comment by jillingk** [comment]
Hi @senturkozer,

This one actually turned out to be a bit more complicated then expected. I'm putting some pressure on now internally to get this fixed so hopefully we can also include this one for the next major release (today/Monday). Apologies for the slow process in getting this fixed!

Best, Jilling
Adyen
