### ISSUE TITLE
How to obtain dynamically the model and serial number of the device?

### ISSUE THREAD

**Issue by g-solarte-alicunde** [Adyen/adyen-java-api-library#1138]
**Java version**: 17.0.5
**Library version**: 20.0.0

Hello Adyen team.

Explanation
We have a need which is to obtain dynamically the model and serial of the device, these two values as you know form the poiId field that is used by your services for some processes, however, we have not been able to obtain this data dynamically, for example, consuming some service.

Reviewing your documentation, we found the following https://docs.adyen.com/api-explorer/postfmapi/1/post/getTerminalsUnderAccount

Which tells us that by passing the account, we could have a list of the devices that are subscribed to this account, but when we decide to use it, it tells us that we do not have permissions. (Attached image)

![image](https://github.com/Adyen/adyen-java-api-library/assets/141035210/20d6523a-293b-48af-a2df-5eb215edffb5)

For some devices the required data would be as for example these:

Model: S1F2
Serial: 000XXXXXXXXXXXXXXXXXXXXXXXXXX

Question
We want to know if you have a service to query the model and serial number of the device, likewise, to give us a clarification on the use of the service mentioned above.

Greetings

**Comment by Aleffio** [comment]
Hi @g-solarte-alicunde ,

Indeed to use the `POS Terminal Management API` you need the `POS Terminal Management API` role assigned to the API Credential you are using: https://docs.adyen.com/point-of-sale/automating-terminal-management/assign-terminals-api/#authentication, otherwise you get the `not allowed` error like you experienced above.

You have two options here:

1. You can assign the role yourself by logging in the Adyen Customer Area like explained here: https://docs.adyen.com/development-resources/api-credentials/#api-permissions
If you don't see or you cannot assign the `POS Terminal Management API` role, please contact our [Support Team](https://ca-test.adyen.com/ca/ca/contactUs/support.shtml?form=other), they should be able to assign the correct role and you will be able to use the getTerminalsUnderAccount endpoint (which is also available in this Java API Library under PosTerminalManagementApi)

2. You can use a different endpoint: `connectedTerminals`: https://docs.adyen.com/point-of-sale/diagnostics/check-cloud-connection/#use-an-api-call which you can find here: https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/service/PosPayment.java#L52

Hope this helps!

Best regards,
Alessio
Adyen

**Comment by edwinalicunde** [comment]
Hello @Aleffio. 
Thanks for the reply. We also have the following question related to the same issue of obtaining the POIID. The priority is to obtain it from the local terminal, at a time of flight. So you would not be connected to the cloud at that time. How can we get the POIID from a terminal, locally? We are currently adding manual, but the idea is for it to be automatic.

**Comment by Aleffio** [comment]
Hi @edwinalicunde ,

I am not sure it is possible as the POIID is a mandatory field for terminal calls,
could you please check with our [Support Team](https://ca-test.adyen.com/ca/ca/contactUs/support.shtml?form=other)?
If there is another endpoint that is missing, we're going to add it to this API Library.

Regards,
Alessio
Adyen
