### ISSUE TITLE
Encryption Missing in Java API library

### ISSUE THREAD

**Issue by fctg-kandasas** [Adyen/adyen-java-api-library#1144]
**Describe the bug**
Like Android and iOS, we dont have options or documentation to perform encryption of Card details at Server Side when sending API requests (https://adyen.github.io/adyen-android/cse/com.adyen.checkout.cse/-card-encrypter/index.html)

**How to reproduce**
-----

**Expected behavior**
There should be a document and option to encrypt card details at Server Side similar to Web, Android and iOS

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 2.14.0

**Additional context**

**Comment by jillingk** [comment]
Hi @fctg-kandasas,

Thanks for reaching out to us with this feature request. The reason we have never implemented this from the libraries side is because encryption is super sensitive and prone to mistakes on the amount of models we have. Plus we figured that giving this control to you will (hopefully) also encourage you to really think about which data is PII and store it as such.

I am seeing some benefits in maybe providing some external construction to implementing encryption in this library though. Perhaps an encryption function in the library that you could call yourselves on a field (deriving the security details once)? I'll create a ticket on our side to investigate this a bit further!

Best, Jilling
Adyen

**Comment by fctg-kandasas** [comment]
Thanks for the consideration but for time being, if we can get some details like algorithm that we should use to encrypt with public key(hoping the one from portal) would help us to solve the problem.

**Comment by jillingk** [comment]
Hi @fctg-kandasas,

You're very welcome. Could you explain me what you're trying to encrypt? It depends a bit on the use case :)

Best, Jilling
Adyen

**Comment by fctg-kandasas** [comment]
> Hi @fctg-kandasas,
> 
> You're very welcome. Could you explain me what you're trying to encrypt? It depends a bit on the use case :)
> 
> Best, Jilling Adyen

Hi @jillingk 

I am trying to encrypt the CardDetails before sending it to Payments API from Kotlin. I am using the public key from Adyen Test Portal -> API Credential -> Client side encryption -> Public Key

![image](https://github.com/Adyen/adyen-java-api-library/assets/20804844/bff5cae9-c845-4cf4-a7b5-4994d62da63b)

**Comment by DjoykeAbyah** [comment]
Hi @fctg-kandasas! Apologies for the delayed reply. 
I wanted to follow up on the Git issue you reported. Are you still encountering the same problem? If not, I'll go ahead and close this issue for now. You can always open a new one if you run into any other issues.

Best regards,

Djoyke
Adyen
