### ISSUE TITLE
[PW-2376] Missing bank account information support

### ISSUE THREAD

**Issue by tddouglas** [Adyen/adyen-java-api-library#330]
With the release of the ACH component, `DefaultPaymentMethodDetails.java` should support serialization of bank account information (both encrypted and unencrypted). E.g:

```json
"paymentMethod" : {
      "type" : "ach",
      "bankAccount" : {
         "bankAccountNumber" : "1234567890",
         "bankLocationId" : "121000358",
         "countryCode" : "US",
         "ownerName" : "John Smith"
      },
},
```

**Comment by andrei-dediu** [comment]
Hello @tddouglas 

I apologise for the late response. I have analyzed your request and indeed the properties are not yet available on the DefaultPaymentMethod. I created a ticket on our internal system and we will have a fix for it in the upcoming updates.

Regards,
Andrei.

**Comment by Aleffio** [comment]
Hello @tddouglas ,
you can now use the AchDetails class instead of the DefaultPaymentMethodDetails:
https://github.com/Adyen/adyen-java-api-library/blob/7c2deb366d21c54e59099369a4db46636123b2ef/src/main/java/com/adyen/model/checkout/details/AchDetails.java#L42
I am closing the ticket, feel free to reopen it if you need more information.

Regards,
Alessio
Adyen
