### ISSUE TITLE
PaymentMethodDetails cannot be deserialized in PaymentsRequest

### ISSUE THREAD

**Issue by jonathanselander** [Adyen/adyen-java-api-library#369]
**Describe the bug**
Running 7.1.0 with kotlin spring boot and trying to implement drop-in checkout. payments() is called with data from the drop-in javascript.

The deserializer fails with this message: 
```
paymentMethod: "Cannot construct instance of `com.adyen.model.checkout.PaymentMethodDetails` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information"
```

I'm no expert but i believe it could be due to all serialize annotations existing in the DefaultPaymentMethodDetails class while the member is of type PaymentMethodDetails that has no annotations.

**How to reproduce**
POST JSON to an endpoint that triggers deserialization of PaymentsRequest

**Comment by Aleffio** [comment]
Hi @jonathanselander,

Thank you for reporting the issue,
we are working on a helper function to deserialize the response of drop-in,
and to create the proper details object depending on the payment method selected:
https://github.com/Adyen/adyen-java-api-library/tree/develop/src/main/java/com/adyen/model/checkout/details

We have an internal ticket about this, and we will pick it up when possible.

Regards,
Alessio
Adyen

**Comment by jonathanselander** [comment]
@Aleffio all right, however, the bug I reported is about the deserializer crashing as is

To solve our issue we had to make a custom Gson deserialize adapter that uses DefaultPaymentMethodDetails for  `@SerializedName("paymentMethod")` in PaymentsRequest

Am i supposed to be able to use drop-in at all with this Java library?

**Comment by Aleffio** [comment]
Hi @jonathanselander ,
indeed at the moment you cannot pass the `state.data.paymentMethod` from the drop-in directly into the PaymentsRequest, your custom adapter is probably a good solution for now, using DefaultPaymentMethodDetails.

Ideally we will use a different details class based on the selected payment method, so that the adapter will deserialize the response from the dropin `state.data.paymentMethod` using a proper details class.
This is something we are still working on, it will be available in one of the next releases.

Regards,
Alessio
Adyen

**Comment by deepu105** [comment]
Guys please note that the solution needs to be able to work with Gson and Jackson as well

**Comment by Aleffio** [comment]
Hi @jonathanselander ,
you can now deserialize data from drop in, into the correct Details classes ApplePayDetails/GooglePayDetails.

Regards,
Alessio
Adyen

**Comment by deepu105** [comment]
@Aleffio when will this be released?
