### ISSUE TITLE
JsonSyntaxException java.text.ParseException: Unparseable date

### ISSUE THREAD

**Issue by tentyp00** [Adyen/adyen-java-api-library#37]
Hello,
When I try to use RecurringDetailsResult object to getting result of recurring.listRecurringDetails(recurringDetailsRequest) i got next error : 

```
com.google.gson.JsonSyntaxException: 2017-07-13T10:15:30+02:00
java.text.ParseException: Unparseable date: "2017-07-13T10:15:30+02:00"
```

It is raised in com.adyen.service.Recurring class in line : 
```
RecurringDetailsResult result = (RecurringDetailsResult)GSON.fromJson(jsonResult, (new TypeToken<RecurringDetailsResult>() {
        }).getType());
```

**Comment by lancergr** [comment]
Hi @tentyp00 

The date format that you sent is the same with the one used in unit tests:
https://github.com/Adyen/adyen-java-api-library/blob/develop/src/test/resources/mocks/recurring/listRecurringDetails-success.json#L2

The problem is most likely caused when using an older version of Gson. Are you running the library standalone or within a project? 
Could you verify that you are loading Gson 2.8.0 or run the library standalone and build using the default pom.xml?

Best Regards,
Giorgos
Adyen

**Comment by tentyp00** [comment]
@lancergr 
Thanks for your message,
You have right with gson version that was a reason of error. After update lib all work. 
Thanks
