### ISSUE TITLE
ResponseEnum not able to handle authorization adjustments

### ISSUE THREAD

**Issue by creichel** [Adyen/adyen-java-api-library#374]
For auth supplements / adjustments, the client SDK tries to map the response `authorized` which is not in the ResponseEnum. Therefore the `response` stays `null`. The issue happens on this line: https://github.com/Adyen/adyen-java-api-library/blob/3fdb789251ccd3ba0c7997a718ad34cc259f09f1/src/main/java/com/adyen/model/modification/ModificationResult.java#L90
 
This leads to refused adjustments when relying on the `response` of an adjustment.

**Comment by Aleffio** [comment]
Hi @creichel ,

Thanks for opening the issue.
we released a new library version: 8.0.0 https://github.com/Adyen/adyen-java-api-library/releases/tag/8.0.0
the response field has been changed to be String, so that it can handle any value.

I am closing the issue, since it is now solved, feel free to reopen it if you still experience problems with ModificationResult.
Kind Regards,
Alessio

Adyen

**Comment by chrisovergaauw** [comment]
Hi Aleffio,

Changing the response field from an enum to a String opens up a new issue.
We implement logic based on the response code and this forces us to compare the response to something hardcoded on the client side.

Please, reinstate the enum or provide an alternative list of constants for us to consume.
