### ISSUE TITLE
narrow down exceptions thrown by terminalLocalAPI's request method

### ISSUE THREAD

**Issue by chrisovergaauw** [Adyen/adyen-java-api-library#592]
Hi,

Our error handling becomes rather ugly due to the broad Exception declaration on this method.
I'm sure it can be narrowed down to something more sensible. 

https://github.com/Adyen/adyen-java-api-library/blob/71c070e9d818a38fbcd8fe5fb062748a94d92443/src/main/java/com/adyen/service/TerminalLocalAPI.java#L58

regards,
Chris

**Comment by AlexandrosMor** [comment]
Hello @chrisovergaauw,

If I understand the issue here is that the error handling is not that clear and it could be more specific? Could you give us an example? If you have some suggestions it would be nice to add the code by opening a pull request following the  [contribution guidelines](https://github.com/Adyen/adyen-java-api-library/blob/2109a3645f858ecdfd7a606838acabde45ab55bd/CONTRIBUTING.md)

kind regards,
Alexandros
Adyen

**Comment by chrisovergaauw** [comment]
Hi Alex,

You can just compare it to the cloud communication to get a sense of a more logical approach.
it declares IOException and ApiException.
that makes a whole lot more sense than a general Exception.

We've decided against using the local integration after all, so for me personally this is no longer an issue.
