### ISSUE TITLE
java.net.UnknownHostException when setting proxy authentication credentials

### ISSUE THREAD

**Issue by sushengloong** [Adyen/adyen-java-api-library#615]
**Describe the bug**
I followed this [instruction](https://github.com/Adyen/adyen-java-api-library#proxy-configuration) to configure proxy for the Adyen client. However, the proxy requires authentication and when I set the proxy host to  `https://USERNAME:PASSWORD@proxy.example.com` I got `java.net.UnknownHostException: https://USERNAME:PASSWORD@proxy.example.com: nodename nor servname provided, or not known`.

This seems to be a bug. Otherwise, what is the correct way to set proxy authentication credentials?

**How to reproduce**
See above

**Expected behavior**
I should be able to call Adyen via the authenticated proxy successfully.

**Desktop (please complete the following information):**
 - Java Version: 11.0.12
 - Library Version: 16.0.0

**Comment by AlexandrosMor** [comment]
Hello @sushengloong,

Thank you for opening this issue. The error that you mention looks like it is the way that the proxy is created. 
Could you please follow this [guide](https://blogs.oracle.com/wssfc/post/handling-proxy-server-authentication-requests-in-java) in order to create the proxy ? Please let us know if this helps  

kind regards,
Alexandros
Adyen

**Comment by SrinivasKG1** [comment]
@sushengloong did you manage to fix this issue

**Comment by sushengloong** [comment]
@SrinivasKG1 No, I ended up integrating with the HTTP API directly instead of using this library.
