### ISSUE TITLE
expiry year changed from full year to last 2 digits in version 18.0.0

### ISSUE THREAD

**Issue by aifrim-tgtg** [Adyen/adyen-java-api-library#767]
**Describe the bug**
https://github.com/Adyen/adyen-java-api-library/pull/754/files#diff-0a9703767a2bf020a556b25adf749d520239626bf3a9a9763bcf0389d8f79739R116

this commit changed the expiry year for a stored card. Before, it was all 4 digits: 2023. In version 18.0, this transformed into 23. This is a breaking change, would be nice to have this mentioned in the release notes.

**Comment by jillingk** [comment]
Hi @aifrim-tgtg,

Thanks for providing the example. It's a bit weird that this change has suddenly happened, as I don't think it was intentional perse. I'm going to investigate this further as we should really catch things like this since it actually impacts you. Apologies for the troubles!

Best, Jilling
Adyen
