### ISSUE TITLE
Nonce Initial Vector Block Random Function Replacement

### ISSUE THREAD

**Issue by ykalayy** [Adyen/adyen-java-api-library#775]
**Java version**: 11
**Library version**: 18.0.0

**Is your feature request related to a problem? Please describe.**
I think It is not a problem. Might be a question. Isn't replacing new Random with singleton SecureRandom much safer?

**Describe the solution you'd like**
Hi, I am new to this repo.
Isn't safer to use singleton SecureRandom instead of new Random for each IV nonce block generation.

**Describe alternatives you've considered**
Even I think the current implementation is safe. Changing nonce initial vector generation with singleton secure random should be much safer whenever especially we use CBC.
**NexoCrypto.java**
```java
  /**
     * Generate a random iv nonce
     */
    private byte[] generateRandomIvNonce() {
        byte[] ivNonce = new byte[NEXO_IV_LENGTH];
        new Random().nextBytes(ivNonce);
        return ivNonce;
    }
```
TO
```java
    /**
     * Generate a random iv nonce
     */
    private byte[] generateRandomIvNonce() {
        byte[] ivNonce = new byte[NEXO_IV_LENGTH];
        SECURE_RANDOM.nextBytes(ivNonce);
        return ivNonce;
    }
```

**Additional context**
None

**Comment by jillingk** [comment]
Hey @ykalayy,

Thanks a lot for contributing! From what I'm reading it seems indeed that simply leveraging Random() for IVnonce might be vulnerable against attacks where adversaries guess this value to break CBC (which would be feasible with random?). Besides the predictability of Random(), it also seems we might also benefit from larger sample group so that we never encounter the same IV twice.

I'm going to pass this onto someone who's more into this stuff since I'm not quite the crypto guru, however your solution looks all good to me. Very good job spotting this one!

Best, Jilling
Adyen

**Comment by ykalayy** [comment]
Hi @jillingk 
Thanks for the response. I keep following the PR. If any objection, I think we can update the PR together

Thanks, Yusuf
