### ISSUE TITLE
ThemeId parameter in CreatePaymentLinkRequest

### ISSUE THREAD

**Issue by LewisWSoftwire** [Adyen/adyen-java-api-library#784]
**Is your feature request related to a problem? Please describe.**
Version 67 of the checkout API introduced the themeId parameter to payment link requests, this was [added to the nodeJS library](https://github.com/Adyen/adyen-node-api-library/blob/9943b41589db1017abb0a1639cb3d03ea0aab63c/src/typings/checkout/createPaymentLinkRequest.ts#L145) but appears to have been missed in the Java library.

**Describe the solution you'd like**
I'd like the themeId parameter to be added to CreatePaymentLinkRequest.

**Describe alternatives you've considered**
I've created a subclass that adds this parameter in the project that I'm working on which seems to work so I'll use that until there's an official update.

**Additional context**
The themeId has already been [added to the payment link resource](https://github.com/Adyen/adyen-java-api-library/blob/main/src/main/java/com/adyen/model/checkout/PaymentLinkResource.java#L1055).

**Comment by jillingk** [comment]
Hi @LewisWSoftwire,

Thanks a lot for reaching out to us with this issue. We are indeed missing some parameters in some classes since it's quite some work to keep all the models up to date. However, we are in the middle of an automation process with the Java library so hopefully soon everything will be up to date (and stay that way). In the meantime I have updated the CreatePaymentLinkRequest class so that with the next release you can use the themeId parameter, regardless of how far we are with the automation project.

Best, Jilling
Adyen

**Comment by LewisWSoftwire** [comment]
Automating the process sounds like it will be great when it's done, thanks for updating it manually in the meantime!
