### ISSUE TITLE
[PW-7236] AbortRequest - Response is null

### ISSUE THREAD

**Issue by hokrobert** [Adyen/adyen-java-api-library#814]
**Describe the bug**
When implementing the Cancellation of an in progress payment transaction (see https://docs.adyen.com/point-of-sale/cancel-a-transaction) the docs state, that the http status code is 200 and the body is null. 
With this behavior the TerminalResponse object is null, which makes it impossible for an integration to check if the cancellation was successful or not.

The described behavior is clearly visible in the code:

AdyenHttpClient.request. The return value is the response body.
[https://github.com/Adyen/adyen-java-api-library/blob/5791e6103c2bb2856e7344b9c6441f24b58c87ee/src/main/java/com/adyen/httpclient/AdyenHttpClient.java#L118](url)

The calling method 
TerminalLocalApi.request checks if the string is != null or empty. If so it returns null.
[https://github.com/Adyen/adyen-java-api-library/blob/5791e6103c2bb2856e7344b9c6441f24b58c87ee/src/main/java/com/adyen/service/TerminalLocalAPI.java#L68](url)

**How to reproduce**
Implement the cancellation request. Inspect the response.

**Expected behavior**
The java library should give some clue about if the request was successful or not. 

**Desktop (please complete the following information):**
 - Java Version: 11.0.14.1
 - Library Version: 18.1.0

**Comment by acampos1916** [comment]
Thanks for opening this issue @hokrobert. Looks like indeed the library will return null on cancellation, so there's no way to verify that it was successful. We've opened an internal ticket to look into this.

**Comment by jillingk** [comment]
Hi @hokrobert,

Thanks for reaching out to us with this issue. You are right that the library does not send back a body upon successfully making an abort-request. This is the case, because the API does not return any body back at all for this specific request. Instead you can verify the status of the abort-request by making a transaction-status request afterwards, as specified in the [documentation](https://docs.adyen.com/point-of-sale/cancel-a-transaction#cancel-from-register).

The reason we don't really want to implement a method to get the http status code in this case, is because we already implemented specific error-handling for every non 200 code. Therefore, you can simply check if the request was successful by catching the errors with a try-catch block and act accordingly on that.

I'm still not too sure why for this specific request the Terminal API does not return any body, however I'm suspecting it has something to do with the general Nexo standards that we follow for this API.

Best, Jilling
Adyen
